import React from 'react'

const FinancialPlanning = () => {
    return (
        <div className='text-center text-light bg-dark' >
            <h3 className='mt-3'>
                FINANCIAL PLANNING
            </h3>
            <p className='m-3'>
                LET'S PLAN YOUR FINANCES
                THE RIGHT WAY. EVERY INDIVIDUAL HAS DIFFERENT NEEDS AT DIFFERENT STAGES OF LIFE. AT IGI LIFE, WE BELIEVE IN PROTECTING YOUR DREAMS AT VARIOUS STAGES OF LIFE WITHOUT COMPROMISING ON YOUR NEEDS THROUGH ¬FINANCIAL RESOURCES. YOU DO NOT HAVE TO THINK TWICE TO LIVE YOUR DREAMS. WE PRESENT TO YOU, ABL SMART FUTURE PLAN WITH VITALITY. YOU CAN GAIN CONTROL OVER YOUR COVERAGE, CHOOSE YOUR BENEFIT AMOUNT & EARN REWARDS, ALL WHILE HELPING TO IMPROVE YOUR HEALTH WITH IGI LIFE VITALITY.
            </p>

        </div>
    )
}

export default FinancialPlanning